### ISSUE TITLE
Typo :)

### ISSUE THREAD

**Issue by Shireku** [poosh/KF-ScrnWeaponPack#8]
Приветствую. Нашёл опечатку.

Failed to load 'Class ScrnWeaponPack.ScrnRPG': Failed to find object 'Class ScrnWeaponPack.ScrnRPG'
Failed to load 'Class ScrnWeaponPack.ScrnRPGPickup': Failed to find object 'Class ScrnWeaponPack.ScrnRPGPickup'

**Comment by poosh** [comment]
ScrnRPG переименован просто в RPG. Старый РПГ убран из мода.
